name: adcc-dev
channels:
  - conda-forge
dependencies:
  - mkl
  - mkl-devel
  - python
  - gcc_linux-64 =9.4
  - gxx_linux-64 =9.4
  - numpy
  - scipy
  - tqdm
  - pandas
  - matplotlib-base
  - h5py
  - opt_einsum
  - pybind11
  - libtensorlight
  - cppe
  - pytest
  - pytest-cov
  - pyyaml
  - lcov
